### ISSUE TITLE
Confusing version property name in readme

### ISSUE THREAD

**Issue by raymondchen625** [dropwizard/dropwizard-testing-junit4#68]
I found the version property in the `README.md` file a little bit confusing:

```
<dependency>
  <groupId>io.dropwizard.modules</groupId>
  <artifactId>dropwizard-testing-junit4</artifactId>
  <version>${dropwizard.version}</version>
</dependency>
```

The `dropwizard.version` is usually used in the [dropwizard](https://github.com/dropwizard/dropwizard) repo, which releases in its own cadence. At the moment, there is a `3.0.2` release of dropwizard, but no such version on `dropwizard-testing-junit4`.

Consider renaming it to something like `${dropwizard-testging-junit4.version}`.

**Comment by joschi** [comment]
@raymondchen625 Thanks for raising this issue!

In this case, the property name is intentional as it refers to the version of the Dropwizard project and not to the version of _this_ project (which should trail the upstream project's version anyway).

The fact that there's no version 3.0.2 and 4.0.2 of this project yet is a plain oversight during the release of Dropwizard 3.0.2 and 4.0.2.

**Comment by joschi** [comment]
Both releases will be available shortly on Maven Central.

- https://github.com/dropwizard/dropwizard-testing-junit4/releases/tag/v3.0.2
- https://github.com/dropwizard/dropwizard-testing-junit4/releases/tag/v4.0.2

**Comment by raymondchen625** [comment]
@joschi Thanks for releasing `3.0.2` and `4.0.2`. Are they still in the process of being published to maven central?

**Comment by joschi** [comment]
Yeah, that was my fault. I didn't ensure the artifacts were pushed.

This time they should really end up soon on Maven Central:

- https://github.com/dropwizard/dropwizard-testing-junit4/actions/runs/6501005903
- https://github.com/dropwizard/dropwizard-testing-junit4/actions/runs/6500995715
